import { Assistant } from "next/font/google";
import "./globals.css";

const assistant = Assistant({
    variable: "--font-assistant",
    subsets: ["latin"],
    display: "swap", // optional: improves rendering behavior
});

export const metadata = {
    title: "ROG Antibot #HOME",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${assistant.variable} font-sans antialiased`}>
                {children}
            </body>
        </html>
    );
}
